### ISSUE TITLE
Issue with setting class prefix

### ISSUE THREAD

**Issue by Ko-Sit** [muenzpraeger/sfdx-plugin#123]
Hi, I am getting the error while trying to set custom class prefix

`
sfdx muenzpraeger:swagger:import -d . -p http://petstore.swagger.io/v2/swagger.json -c Dummy `    
            
`ERROR running Import:  Command failed: java -jar /Users/kosit/.local/share/sfdx/node_modules/muenzpraeger-sfdx-plugin/resources/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l apex -o . -s --classPrefix=Dummy
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [--classPrefix=Dummy]
	at io.airlift.airline.Cli.validate(Cli.java:148)
	at io.airlift.airline.Cli.parse(Cli.java:116)
	at io.airlift.airline.Cli.parse(Cli.java:97)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
`

sfdx version: sfdx-cli/7.52.0-c5ad5c3eff darwin-x64 node-v10.15.3
plugin version: muenzpraeger-sfdx-plugin 0.2.0
pc: Mac OS X 10.15.4

**Comment by muenzpraeger** [comment]
There seems to be an issue with the underlying build. As the Swagger generator is somewhat outdated I won't be able to fix that. For now I've just released a new version that doesn't take the `-c` parameter.

A potential alternative is to directly uses the new [openapi-tools-cli generator](https://github.com/openapitools/openapi-generator-cli). I'll also validate if it makes sense to keep this command in this CLI plugin, or just refer to the aforementioned CLI.
