### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SalesforceBobLightning** [muenzpraeger/sfdx-plugin#194]
When I try and install I get this error message

> PS C:\projects\company\client\feature-branch> sfdx plugins:install @muenzpraeger/sfdx-plugin
> This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
> Finished digital signature check.
> Error: EISDIR: illegal operation on a directory, read
>     at Object.readSync (fs.js:568:3)
>     at tryReadSync (fs.js:353:20)
>     at Object.readFileSync (fs.js:390:19)
>     at onUnexpectedError (C:\Users\Me\AppData\Local\sfdx\client\7.69.0-1101929cd1\node_modules\yarn\lib\cli.js:92560:100)
>     at C:\Users\Me\AppData\Local\sfdx\client\7.69.0-1101929cd1\node_modules\yarn\lib\cli.js:92672:9
> Installing plugin @muenzpraeger/sfdx-plugin... !
> Error: yarn add @muenzpraeger/sfdx-plugin@latest --non-interactive --mutex=file:C:/Users/Me/AppData/Local/sfdx/yarn.lock --preferred-cache-folder=C:/Users/Me/AppData/Local/sfdx/yarn --check-files exited with code 1
>     at ChildProcess.<anonymous> (C:/Users/Me/AppData/Local/sfdx/client/7.69.0-1101929cd1/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)

**Comment by muenzpraeger** [comment]
That's a Windows filesystem issue. Not much I can do...

**Comment by j-fischer** [comment]
@SalesforceBobLightning I know it is late, but I ran into this issue and was able to resolve it by deleting the `yarn.lock` folder in `C:/Users/Me/AppData/Local/sfdx/` manually and then re-running the install command. 

I hope this helps anyone else running into this issue, it applies to any plugin installation.
