### ISSUE TITLE
Problems with refreshAuth

### ISSUE THREAD

**Issue by lmfmsilva** [muenzpraeger/sfdx-plugin#4]
Hi,
Installed your tools (Ubuntu):
sfdx plugins:install muenzpraeger-sfdx-plugin

When I run your basic test:
sfdx muenzpraeger:swagger:import -d . -p http://petstore.swagger.io/v2/swagger.json

**ERROR running Import:  Cannot read property 'refreshAuth' of undefined**

Other commands
sfdx -v
sfdx-cli/6.15.0-ded9afdffb (linux-x64) node-v8.9.4

sfdx plugins
muenzpraeger-sfdx-plugin 0.2.0

**Comment by muenzpraeger** [comment]
Have you checked that your local sfdx auth to your Dev Hub is valid?
