### ISSUE TITLE
openapi-generator-cli.jar is missing despite of successful installation

### ISSUE THREAD

**Issue by klmazur22** [muenzpraeger/sfdx-plugin#420]
After successful installation (_changed 104 packages, and audited 105 packages in 19s_), I run _sfdx mzpr:swagger:import -d . -p FlightOffersSearch_v2_Version_2.5_swagger_specification.json_, but getting this error:

Command failed: java -jar /Users/kyrylo/.local/share/sfdx/node_modules/@muenzpraeger/sfdx-plugin/resources/openapi-generator-cli.jar generate -i FlightOffersSearch_v2_Version_2.5_swagger_specification.json -l apex -o . -s
Error: Unable to access jarfile /Users/kyrylo/.local/share/sfdx/node_modules/@muenzpraeger/sfdx-plugin/resources/openapi-generator-cli.jar

One I check the resources folder, I can see only one file - _swagger-codegen-cli.jar_, so _openapi-generator-cli.jar_ is actually missing.

Please let me know if do anything wrong.

**Comment by muenzpraeger** [comment]
Thanks for trying things out. Sadly I didn't maintain this package for a long time - and with that I'm not even sure where to look at these days.

I recommend to use the [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator) directly if you need Apex, as this is the best option moving forward. An alternative approach is to use [Flow with External Services](https://help.salesforce.com/s/articleView?id=sf.external_services.htm&type=5).

I'll set the repo to `archived`. Sorry that it created more work for you.
