### ISSUE TITLE
support updating package version numbers

### ISSUE THREAD

**Issue by Feldhacker** [muenzpraeger/sfdx-plugin#7]
Being able to update the apiVersion is great.  It would be useful to also be able to update dependent package version numbers as well.

For example, when an Apex class references another class that is in a managed package, then the version number of the managed package will be added to the metadata file as well.  Like:

`<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">`
`    <apiVersion>43.0</apiVersion>`
`    <packageVersions>`
`        <majorNumber>216</majorNumber>`
`        <minorNumber>2</minorNumber>`
`        <namespace>FinServ</namespace>`
`    </packageVersions>`
`    <status>Active</status>`
`</ApexClass>`

This class was created / last updated when the FinServ package was at version 216.2, but the current version is 218.5.  

Perhaps the api:set command could be enhanced to also support updating package version numbers?  Perhaps by accepting arguments such as:  
api:set -namespace FinServ -majorNumber 218 -minorNumber 5

**Comment by muenzpraeger** [comment]
Although it's an interesting use case I'm wondering how often it appears. Feel free to PR the needed changes.
