### ISSUE TITLE
Problems with api:set

### ISSUE THREAD

**Issue by vjlourdu** [muenzpraeger/sfdx-plugin#9]
Hi,

I am trying to upgrade the API version in a DX project to the latest version, and keep getting following error:
Followed the suggestion as well and it is not working. 
https://github.com/muenzpraeger/sfdx-plugin/issues/6

sfdx muenzpraeger:source:api:set Reading content of package directories. ! Error: ENOENT: no such file or directory, scandir ! 'C:\Path_To_Project\.sfdx\sfdx-config.json\force-app'

Only when I specify the version directly, I am seeing another error:
sfdx muenzpraeger:source:api:set -a 45.0 ERROR running SourceApiSet: Cannot read property 'validateApiVersion' of undefined

All commands were executed in the windows command line inside the project root folder.

Any idea what I am missing here? Any help would be greatly appreciated.

Thanks!

**Comment by vjlourdu** [comment]
I am getting this error while updating the plugins using sfdx as well.

warning "@muenzpraeger/sfdx-plugin > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
sfdx-cli: Updating plugins... done

**Comment by muenzpraeger** [comment]
Fixed with the new version `0.5.0`, sorry for the late reply.
